### ISSUE TITLE
Not working with React 16

### ISSUE THREAD

**Issue by ixrock** [Wildhoney/ReactShadow#36] opened 2017-10-04 23:04 UTC
Error related to https://github.com/Wildhoney/ReactShadow/blob/master/src/react-shadow.js#L293
and might some others..

**Comment by Wildhoney** [comment] 2017-10-05 08:43
Thanks @ixrock &mdash; I'll take a look at supporting React 16.x 👍

**Comment by gurkerl83** [comment] 2017-10-05 09:41
Hi, the problem is related to 

https://github.com/Wildhoney/Keo/issues/37

DOM Factories are from React 16 upwards available in an external react library called react-dom-factories.

Thanks!

**Comment by Wildhoney** [comment] 2017-10-10 07:57
See https://github.com/facebook/react/pull/11037

Rendering into a shadow boundary has been resolved, but not yet released. Will update `ReactShadow` once it has 👍

**Comment by natew** [comment] 2017-11-09 18:43
Just wondering, seems like that was merged. Should this "just work" again? Or will this library need updates? If someone can confirm it should work I can give it a test.

**Comment by Wildhoney** [comment] 2017-11-10 11:10
There weren't any substantial changes required to make it work with React 16.1.x. However, I've updated the codebase and pushed as `v16.1.0` so we can mirror React versions.

All should be good now 👍 Please create new tickets for any issues you may find.

**Closed by Wildhoney** 2017-11-10 11:10 UTC
